### PR TITLE
Add local matmul precision test

### PR DESCRIPTION
**Pull request by robinvanemden**
The local matmul test in the current pull request fails (for me) when not also adding std::cout.precision(20) to onnx_backend_tests_runner.cc (I also added it to main.cc).

The data is generated by a basic Python script that I use to create simple models together with their input and onnxruntime generated output.

It is probably a good idea to double check whether a precision of 20 offers the right balance between c file size and model precision.

### CODE REVIEW

**Comment by kraiskil** [comment]
This does indeed show the failure due to precision - the tests fail. Now we would also need the fix so that the tests pass again ;)

Also, I realized since there is more than one contributor now, onnx2c needs a license, so I added one. If the terms are acceptable to you, please rebase this PR on master and add yourself to the blamelist.

**Comment by robinvanemden** [comment]
The terms seem fine to me! I rebased the PR on master, and added the decimal precision fix as well to make sure the test now passes.

**Comment by kraiskil** [comment]
Merged, thanks! :+1: 

I did a bit of sin, and rebased your commits on master to get rid of the merge commit message.
Also, I switched the order so that the fix commit comes first. This way if bisecting is needed, the test suite won't fail because of this known issue you fixed.
Since github tells me your fork is the only one, this history rewriting shouldn't be that bad a thing. Sorry for the trouble!

**Comment by robinvanemden** [comment]
No problem at all - your reordering of the commit makes sense 😄 
Thanks for merging!

**Pull request closed without merging**
